apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-app
spec:
  replicas: 2  # Runs 2 instances of the app
  selector:
    matchLabels:
      app: weather
  template:
    metadata:
      labels:
        app: weather
    spec:
      containers:
      - name: backend
        image: 31hardik/weatherapp-backend:latest
        ports:
        - containerPort: 5001
      - name: frontend
        image: 31hardik/weatherapp-frontend:latest
        ports:
        - containerPort: 3001

---
apiVersion: v1
kind: Service
metadata:
  name: weather-service
spec:
  selector:
    app: weather
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
